[build]
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = '''
      default-src 'self';
      base-uri 'self';
      connect-src 'self';
      form-action 'none';
      frame-src 'none';
      frame-ancestors 'none';
      child-src 'none';
      font-src 'self' https://cdn.gummibeer.dev;
      img-src 'self' https://img.gummibeer.dev https://cdn.gummibeer.dev;
      media-src 'none';
      object-src 'none';
      script-src 'self' 'unsafe-eval' https://cdn.gummibeer.dev;
      style-src 'self' 'unsafe-inline' https://cdn.gummibeer.dev
    '''

[[headers]]
  for = "*.rss"
  [headers.values]
    Content-Type = "application/rss+xml"

[[headers]]
  for = "*.atom"
  [headers.values]
    Content-Type = "application/atom+xml"

[[headers]]
  for = "/css/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[headers]]
  for = "/images/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[headers]]
  for = "/js/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[redirects]]
  from = "https://gummibeer.netlify.app/*"
  to = "https://gummibeer.dev/:splat"
  status = 301
  force = true

[[plugins]]
  package = "netlify-plugin-minify-html"
  [plugins.inputs]
    contexts = [
      'production'
    ]
  [plugins.inputs.minifierOptions]
    html5 = true
    removeComments = true
    collapseWhitespace = true
    conservativeCollapse = true
    keepClosingSlash = false
